# Generated by Django 6.0.2 on 2026-04-14 20:47

import uuid
from django.db import migrations, models


def migrate_playlist_tracks(apps, schema_editor):
    Playlist = apps.get_model('musewave', 'Playlist')
    Track = apps.get_model('musewave', 'Track')
    PlaylistTrack = apps.get_model('musewave', 'PlaylistTrack')

    connection = schema_editor.connection
    table_names = connection.introspection.table_names()
    old_table = 'musewave_playlist_tracks'
    if old_table not in table_names:
        return

    with connection.cursor() as cursor:
        cursor.execute(f'SELECT playlist_id, track_id FROM {old_table}')
        rows = cursor.fetchall()

    playlist_order = {}
    for playlist_id, track_id in rows:
        playlist = Playlist.objects.filter(pk=playlist_id).first()
        track = Track.objects.filter(pk=track_id).first()
        if not playlist or not track:
            continue

        order_value = playlist_order.get(playlist_id, 0)
        playlist_order[playlist_id] = order_value + 1

        PlaylistTrack.objects.get_or_create(
            playlist=playlist,
            track=track,
            defaults={
                'id': uuid.uuid4(),
                'order': order_value,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('musewave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=models.CASCADE, related_name='playlist_tracks', to='musewave.playlist')),
                ('track', models.ForeignKey(on_delete=models.CASCADE, related_name='playlist_tracks', to='musewave.track')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('playlist', 'track'), ('playlist', 'order')},
            },
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(
                blank=True,
                through='musewave.PlaylistTrack',
                through_fields=('playlist', 'track'),
                related_name='in_playlists',
                to='musewave.track'
            ),
        ),
        migrations.RunPython(migrate_playlist_tracks, migrations.RunPython.noop),
    ]
