# Generated by Django 5.0.1 on 2026-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musewave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_fileforge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_fileforge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_fileforge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_fileforge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='header_fileforge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
