# Generated by Django 5.0.1 on 2026-05-01 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('file_id', models.CharField(help_text='Google Drive file ID', max_length=256, unique=True)),
                ('folder_id', models.CharField(help_text='Google Drive folder ID', max_length=256)),
                ('category', models.CharField(choices=[('track_audio', 'Track Audio'), ('track_cover', 'Track Cover'), ('album_cover', 'Album Cover'), ('user_avatar', 'User Avatar'), ('user_header', 'User Header')], max_length=20)),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('url', models.URLField(blank=True, help_text='Proxy or direct URL', max_length=1024)),
                ('resource_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('user', 'User')], max_length=20)),
                ('resource_id', models.CharField(help_text='ID of the related resource in Django DB', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
